[demo]
aoi_key = "resources/reference.geojson"

[[demo.aois]]
id = 1
name = "AOI 1"
ndvi = "resources/NDVI_1_2024-01-01.tiff"
msavi = "resources/MSAVI_1_2024-01-01.tiff"

[[demo.aois]]
id = 2
name = "AOI 2"
ndvi = "resources/NDVI_2_2024-01-01.tiff"
msavi = "resources/MSAVI_2_2024-01-01.tiff"

[defaults]
start_year = 2019
end_year = 2024

[r2]
endpoint = "${R2_ENDPOINT}"
bucket = "${R2_BUCKET}"
key = "${R2_KEY}"
secret = "${R2_SECRET}"

[cache]
redis_url = "${REDIS_URL}"
