monthly_index = "ndvi"
annual_index = "msavi"

[demo]
aoi_key = "resources/reference.geojson"

[[demo.aois]]
id = 1
name = "AOI 1"
ndvi = "resources/NDVI_1_2024-01-01.tif"
msavi = "resources/MSAVI_1_2024-01-01.tif"

[[demo.aois]]
id = 2
name = "AOI 2"
ndvi = "resources/NDVI_2_2024-01-01.tif"
msavi = "resources/MSAVI_2_2024-01-01.tif"

[defaults]
start_year = 2019
end_year = 2024

[map.fields]
id = "AOI ID"
area_m2 = "Area (m2)"
area_ha = "Area (ha)"
bscore = "B-score"

[r2]
endpoint = "${R2_ENDPOINT}"
bucket = "${R2_BUCKET}"
key = "${R2_KEY}"
secret = "${R2_SECRET}"

[cache]
redis_url = "${REDIS_URL}"

